"use client";

import { motion } from "framer-motion";
import { parseField } from "@/lib/parseField";

/**
 * CoreConceptBlock — The dense explanatory text block.
 * 
 * Features no outer card wrapper to feel more like an open textbook.
 * Optionally includes an Analogy Box if one is provided.
 */

interface AnalogyData {
  text: unknown;
  verified: boolean;
}

interface CoreConceptBlockProps {
  content: unknown;
  analogy?: AnalogyData;
}

export function CoreConceptBlock({ content, analogy }: CoreConceptBlockProps) {
  const parsedContent = parseField(content);
  const parsedAnalogyText = analogy ? parseField(analogy.text) : "";

  return (
    <motion.section 
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-80px" }}
      transition={{ duration: 0.4 }}
      className="flex flex-col gap-4 mt-8"
    >
      {/* Section Label Row */}
      <div className="flex flex-row items-center gap-4">
        <span className="font-sans text-[10px] uppercase tracking-widest text-text-tertiary">
          Core Concept
        </span>
        <div className="w-[32px] h-[1px] bg-border-default" />
      </div>

      {/* Main Explanatory Content */}
      <div className="font-sans text-[14px] text-text-secondary leading-relaxed">
        {parsedContent}
      </div>

      {/* Analogy Box (Conditional) */}
      {analogy && parsedAnalogyText && (
        <div className="mt-2 bg-blue-dim border border-[rgba(90,154,232,0.15)] rounded-lg p-[12px_16px] flex flex-row gap-[10px] items-start">
          <span className="font-sans text-[9px] uppercase font-bold text-blue tracking-wider whitespace-nowrap mt-1">
            Analogy
          </span>
          <span className="font-sans text-[13px] italic text-text-secondary flex-1">
            {parsedAnalogyText}
          </span>
          
          {/* Warning Icon if Analogy is unverified */}
          {!analogy.verified && (
            <div className="group relative flex items-center justify-center mt-1">
              <svg 
                className="w-3 h-3 text-accent cursor-help" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor" 
                strokeWidth={2}
              >
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
              
              {/* Tooltip */}
              <div className="absolute bottom-full right-0 mb-2 w-48 p-2 bg-bg-raised border border-border-default rounded text-[10px] text-text-secondary opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none shadow-lg z-10">
                This analogy is generated by AI and has not been vetted by an expert.
              </div>
            </div>
          )}
        </div>
      )}
    </motion.section>
  );
}
